"""api_usage

Revision ID: 62df52214b09
Revises: a1b2c3d4e5f6
Create Date: 2026-04-13 18:43:50.999285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '62df52214b09'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('last_req', sa.Text(), nullable=True),
    sa.Column('rate_max', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('chat_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ingest_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('query_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('team_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_index('idx_api_usage_team_created', 'api_usage', ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_api_usage_team_created', table_name='api_usage')
    op.drop_table('api_usage')
    # ### end Alembic commands ###

