name: Deploy vLLM
on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/cloudrun-deploy.yml
    with:
      service_name: llama3-vllm
      image_repo: api-registry/vllm
      dockerfile: Dockerfile.vllm
      deploy_region: us-east4
      deploy_flags: >
        --memory=32Gi
        --cpu=8
        --gpu=1
        --gpu-type=nvidia-l4
        --execution-environment=gen2
        --no-cpu-throttling
        --no-gpu-zonal-redundancy
        --min-instances=0
        --max-instances=1
        --startup-probe tcpSocket.port=8080,initialDelaySeconds=240,failureThreshold=1,timeoutSeconds=240,periodSeconds=240
    secrets: inherit
